### ISSUE TITLE
Python 3.5 Issue

### ISSUE THREAD

**Issue by nikolay** [donnemartin/saws#26]
```
Collecting configobj>=5.0.6 (from saws->-r requirements.txt (line 38))
  Using cached configobj-5.0.6.tar.gz
Collecting enum34>=1.0.4 (from saws->-r requirements.txt (line 38))
  Using cached enum34-1.0.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "/private/var/folders/cb/cxxqz_g94jd1x5tjwrklxgd00000gn/T/pip-build-9jvu7ws4/enum34/enum/__init__.py", line 371, in __getattr__
        return cls._member_map_[name]
    KeyError: '_convert'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 3, in <module>
      File "/Users/username/.pyenv/versions/aws/lib/python3.5/site-packages/setuptools/__init__.py", line 12, in <module>
        from setuptools.extension import Extension
      File "/Users/username/.pyenv/versions/aws/lib/python3.5/site-packages/setuptools/extension.py", line 8, in <module>
        from .dist import _get_unpatched
      File "/Users/username/.pyenv/versions/aws/lib/python3.5/site-packages/setuptools/dist.py", line 16, in <module>
        from setuptools.depends import Require
      File "/Users/username/.pyenv/versions/aws/lib/python3.5/site-packages/setuptools/depends.py", line 6, in <module>
        from setuptools import compat
      File "/Users/username/.pyenv/versions/aws/lib/python3.5/site-packages/setuptools/compat.py", line 45, in <module>
        import http.client as httplib
      File "/Users/username/.pyenv/versions/3.5.0/lib/python3.5/http/client.py", line 71, in <module>
        import email.parser
      File "/Users/username/.pyenv/versions/3.5.0/lib/python3.5/email/parser.py", line 12, in <module>
        from email.feedparser import FeedParser, BytesFeedParser
      File "/Users/username/.pyenv/versions/3.5.0/lib/python3.5/email/feedparser.py", line 27, in <module>
        from email import message
      File "/Users/username/.pyenv/versions/3.5.0/lib/python3.5/email/message.py", line 16, in <module>
        from email import utils
      File "/Users/username/.pyenv/versions/3.5.0/lib/python3.5/email/utils.py", line 29, in <module>
        import socket
      File "/Users/username/.pyenv/versions/3.5.0/lib/python3.5/socket.py", line 73, in <module>
        IntEnum._convert(
      File "/private/var/folders/cb/cxxqz_g94jd1x5tjwrklxgd00000gn/T/pip-build-9jvu7ws4/enum34/enum/__init__.py", line 373, in __getattr__
        raise AttributeError(name)
    AttributeError: _convert

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/cb/cxxqz_g94jd1x5tjwrklxgd00000gn/T/pip-build-9jvu7ws4/enum34
```

**Comment by donnemartin** [comment]
Hi Nikolay,

I've been meaning to check out the latest Python, thanks for the bug report :)

Looks like I'll have to scope enum34 to Python <= 3.3, also discussed here: https://github.com/donnemartin/saws/issues/22.

-Donne

**Comment by nikolay** [comment]
@donnemartin Thanks for the great project and responding so quickly!

**Comment by nikolay** [comment]
@donnemartin FYI, it doesn't seem to work on Python 3.4 either.

**Comment by donnemartin** [comment]
Hi Nikolay,

I just tested locally and it seems to be working.  Travis also reports no issues:

https://travis-ci.org/donnemartin/saws

Are you installing with a `virtualenv`?  You might have some permission or dependency issues.  I updated the installation section of the `README` yesterday with some more details:

https://github.com/donnemartin/saws#pip-installation

-Donne

**Comment by nikolay** [comment]
Hmmm, I switched my venv to 3.4.3, it didn't work, but let me try on a clean environment. Sorry for the false alarm! Will check the `README`, too.

**Comment by donnemartin** [comment]
Hi Nikolay,

Odd...yes a clean `virtualenv` would be my next attempt.  I just tried again no problems installing on:

* Python 3.4.3, OSX 10.10.5
* Python 3.4.0, Ubuntu 14.04 LTS

-Donne

**Comment by donnemartin** [comment]
Got around to getting `pyenv` and Python 3.5 running, `SAWS` install on Python 3.5 in a fresh venv seems to work for me.  

I'll hook up Python 3.5 to Travis CI later today and see if it builds.

![](http://i.imgur.com/hkqIOQ0.png)
![](http://i.imgur.com/w0NZm20.png)

**Comment by donnemartin** [comment]
>I'll hook up Python 3.5 to Travis CI later today and see if it builds.

Seems I won't be able to do this yet due to: https://github.com/travis-ci/travis-ci/issues/4794.

**Comment by nikolay** [comment]
@donnemartin It works on 3.4.3, sorry. It was a false alarm caused by some dirty pyenv, I guess.

**Comment by nikolay** [comment]
@donnemartin I understand the Python 3.5 dependency is external. Again, great job!

**Comment by donnemartin** [comment]
@nikolay enum34 is now installed for Python < 3.4.

59e2b60bcf30b7f162fd5870f7f55ecf5a7076dd

**Comment by nikolay** [comment]
@donnemartin Thank you very much!
