### ISSUE TITLE
enum34 shouldn't be installed on Python 3.4+

### ISSUE THREAD

**Issue by victorhooi** [donnemartin/saws#55]
I am running OSX with Python 3.5.

When I try to install `saws` using `pip`, I get:

```
victorhooi@thadeus ~> pip3 install saws
Collecting saws
  Using cached saws-0.2.1.tar.gz
Collecting awscli>=1.7.46 (from saws)
  Using cached awscli-1.8.12-py2.py3-none-any.whl
Collecting click>=4.0 (from saws)
  Using cached click-5.1-py2.py3-none-any.whl
Collecting configobj>=5.0.6 (from saws)
  Using cached configobj-5.0.6.tar.gz
Collecting enum34>=1.0.4 (from saws)
  Using cached enum34-1.0.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "/private/var/folders/9l/r3dzz8551579drqy2j8d6gwm0000gn/T/pip-build-cdj3eth2/enum34/enum/__init__.py", line 371, in __getattr__
        return cls._member_map_[name]
    KeyError: '_convert'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 3, in <module>
      File "/usr/local/lib/python3.5/site-packages/setuptools/__init__.py", line 12, in <module>
        from setuptools.extension import Extension
      File "/usr/local/lib/python3.5/site-packages/setuptools/extension.py", line 8, in <module>
        from .dist import _get_unpatched
      File "/usr/local/lib/python3.5/site-packages/setuptools/dist.py", line 16, in <module>
        from setuptools.depends import Require
      File "/usr/local/lib/python3.5/site-packages/setuptools/depends.py", line 6, in <module>
        from setuptools import compat
      File "/usr/local/lib/python3.5/site-packages/setuptools/compat.py", line 45, in <module>
        import http.client as httplib
      File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 71, in <module>
        import email.parser
      File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/email/parser.py", line 12, in <module>
        from email.feedparser import FeedParser, BytesFeedParser
      File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/email/feedparser.py", line 27, in <module>
        from email import message
      File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/email/message.py", line 16, in <module>
        from email import utils
      File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/email/utils.py", line 29, in <module>
        import socket
      File "/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/socket.py", line 73, in <module>
        IntEnum._convert(
      File "/private/var/folders/9l/r3dzz8551579drqy2j8d6gwm0000gn/T/pip-build-cdj3eth2/enum34/enum/__init__.py", line 373, in __getattr__
        raise AttributeError(name)
    AttributeError: _convert

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/9l/r3dzz8551579drqy2j8d6gwm0000gn/T/pip-build-cdj3eth2/enum34
```

It seems that enum34 doesn't work on Python 3.5:

https://bitbucket.org/stoneleaf/enum34/issues/5/enum34-incompatible-with-python-35

In fact, I don't think it makes sense to install enum34 on Python 3.4+ anyway.

Is there some way to resolve this so that saws will install on Python 3.4 and upwards?

**Comment by donnemartin** [comment]
@victorhooi thanks for the ticket.  This should be fixed in f109bc8f534905797ee44239cb766ea3de4ceb5d but it hasn't been pushed to PyPi yet.  

You can install from that latest GitHub source by running the following:

    pip install git+https://github.com/donnemartin/saws.git

**Comment by akerl** [comment]
Would it be possible to cut a new release that has that fix?

**Comment by donnemartin** [comment]
@akerl sure, I hope to have it out in the next couple of days.

**Comment by donnemartin** [comment]
Just a quick update: this is near the top of my TODO list, just have to package it up, run a few tests, and post to PyPI.  Hopefully by tonight or tomorrow.

**Comment by victorhooi** [comment]
Awesome stuff =).

**Comment by donnemartin** [comment]
Ran into a bug while testing the latest package before posting to PyPI: https://github.com/donnemartin/saws/issues/61

I have a fix in mind, I'll put it in tomorrow.

**Comment by donnemartin** [comment]
0.3.2 posted to PyPI: https://pypi.python.org/pypi/saws
